# Derive from the official cross-rs image for your target
FROM ghcr.io/cross-rs/aarch64-unknown-linux-gnu:edge

# Add the arm64 architecture
RUN dpkg --add-architecture arm64

# Install cross compiler + arm64 target libs
RUN apt-get update && \
    apt-get install --assume-yes --no-install-recommends \
    gcc-aarch64-linux-gnu \
    libfontconfig1-dev:arm64 \
    libfreetype6-dev:arm64 \
    libxkbcommon-dev:arm64 \
    libinput-dev:arm64 \
    libgbm-dev:arm64 \
    libwayland-dev:arm64 \
    libdrm-dev:arm64 \
    libegl1-mesa-dev:arm64 \
    libasound2-dev:arm64 \
    pkg-config

# Configure pkg-config to search the target filesystem instead of the host
ENV PKG_CONFIG_PATH_aarch64_unknown_linux_gnu=/usr/lib/aarch64-linux-gnu/pkgconfig/
ENV PKG_CONFIG_ALLOW_CROSS=1