# POKY_BBLAYERS_CONF_VERSION is increased each time build/conf/bblayers.conf
# changes incompatibly
POKY_BBLAYERS_CONF_VERSION = "2"

BBPATH = "${TOPDIR}"
BBFILES ?= ""

# This should be written on ocarinaos.bblayers.conf. Mentioning here for redundancy.
BBLAYERS ?= " \
  /home/build/work/poky/meta \
  /home/build/work/poky/meta-poky \
  /home/build/work/poky/meta-yocto-bsp \
  /home/build/work/meta-raspberrypi \
  /home/build/work/meta-openembedded/meta-oe \
  /home/build/work/meta-openembedded/meta-python \
  /home/build/work/meta-ocarina \
"
