require conf/distro/poky.conf

DISTRO = "ocarinaos"
DISTRO_NAME = "OcarinaOS"
DISTRO_CODENAME = "ocarina"
HOSTNAME = "ocarinaos"
MACHINE_HOSTNAME = "ocarinaos"
OCARINA_GIT_HASH ?= "unknown"
DISTRO_VERSION = "2.0.0+${OCARINA_GIT_HASH}"
DISTRO_VERSION[vardepsexclude] = "OCARINA_GIT_HASH"
