export component Info inherits PopupWindow {
    in-out property <string> guiVersion;
    in-out property <string> listenerVersion;
    in-out property <string> osVersion;

    close-policy: close-on-click-outside;
    Rectangle { 
        height:100%; width: 100%; 
        background: #884fbbe9; 
        border-width: 4px;
        border-color: #a189da;
        border-radius: 30px;
        drop-shadow-blur: 20px;
        drop-shadow-color: #000000aa;
    }

    VerticalLayout {
        alignment: center;
        padding: 16px;
        spacing: 32px;
        HorizontalLayout {
            alignment: space-evenly;
            Text { text: "OcarinaOS Version:"; font-size: 18px; }
            Text { text: root.osVersion; font-size: 18px; font-weight: FontWeight.extra-bold; }
        }
        HorizontalLayout {
            alignment: space-evenly;
            Text { text: "OcarinaGUI Version:"; font-size: 18px; }
            Text { text: root.guiVersion; font-size: 18px; font-weight: FontWeight.extra-bold; }
        }
        HorizontalLayout {
            alignment: space-evenly;
            Text { text: "OcarinaListener Version:"; font-size: 18px; }
            Text { text: root.listenerVersion; font-size: 18px; font-weight: FontWeight.extra-bold; }
        }
    }

    x: 237px; y: 100px; width: 550px; height: 400px;
}