export component Note inherits Rectangle {
    width: 125px;
    height: 400px;

    in property <string> note: "C4";

    if note == "C4" : Image {
        source: @image-url("imgs/notes/C4.svg");
        horizontal-alignment: center;
        vertical-alignment: center;
    }

    if note == "C#4" : Image {
        source: @image-url("imgs/notes/C#4.svg");
        horizontal-alignment: center;
        vertical-alignment: center;
    }

    if note == "D4" : Image {
        source: @image-url("imgs/notes/D4.svg");
        horizontal-alignment: center;
        vertical-alignment: center;
    }

    if note == "D#4" : Image {
        source: @image-url("imgs/notes/D#4.svg");
        horizontal-alignment: center;
        vertical-alignment: center;
    }

    if note == "E4" : Image {
        source: @image-url("imgs/notes/E4.svg");
        horizontal-alignment: center;
        vertical-alignment: center;
    }

    if note == "F4" : Image {
        source: @image-url("imgs/notes/F4.svg");
        horizontal-alignment: center;
        vertical-alignment: center;
    }

    if note == "F#4" : Image {
        source: @image-url("imgs/notes/F#4.svg");
        horizontal-alignment: center;
        vertical-alignment: center;
    }

    if note == "G4" : Image {
        source: @image-url("imgs/notes/G4.svg");
        horizontal-alignment: center;
        vertical-alignment: center;
    }

    if note == "G#4" : Image {
        source: @image-url("imgs/notes/G#4.svg");
        horizontal-alignment: center;
        vertical-alignment: center;
    }

    if note == "A4" : Image {
        source: @image-url("imgs/notes/A4.svg");
        horizontal-alignment: center;
        vertical-alignment: center;
    }

    if note == "A#4" : Image {
        source: @image-url("imgs/notes/A#4.svg");
        horizontal-alignment: center;
        vertical-alignment: center;
    }

    if note == "B4" : Image {
        source: @image-url("imgs/notes/B4.svg");
        horizontal-alignment: center;
        vertical-alignment: center;
    }
    
    if note == "C5" : Image {
        source: @image-url("imgs/notes/C5.svg");
        horizontal-alignment: center;
        vertical-alignment: center;
    }

    if note == "C#5" : Image {
        source: @image-url("imgs/notes/C#5.svg");
        horizontal-alignment: center;
        vertical-alignment: center;
    }
    
    if note == "D5" : Image {
        source: @image-url("imgs/notes/D5.svg");
        horizontal-alignment: center;
        vertical-alignment: center;
    }
    
    if note == "D#5" : Image {
        source: @image-url("imgs/notes/D#5.svg");
        horizontal-alignment: center;
        vertical-alignment: center;
    }
    
    if note == "E5" : Image {
        source: @image-url("imgs/notes/E5.svg");
        horizontal-alignment: center;
        vertical-alignment: center;
    }
    
    if note == "F5" : Image {
        source: @image-url("imgs/notes/F5.svg");
        horizontal-alignment: center;
        vertical-alignment: center;
    }

    
    if note == "F#5" : Image {
        source: @image-url("imgs/notes/F#5.svg");
        horizontal-alignment: center;
        vertical-alignment: center;
    }
    
    if note == "G5" : Image {
        source: @image-url("imgs/notes/G5.svg");
        horizontal-alignment: center;
        vertical-alignment: center;
    }
    
    if note == "G#5" : Image {
        source: @image-url("imgs/notes/G#5.svg");
        horizontal-alignment: center;
        vertical-alignment: center;
    }
    
    if note == "A5" : Image {
        source: @image-url("imgs/notes/A5.svg");
        horizontal-alignment: center;
        vertical-alignment: center;
    }
    
    if note == "A#5" : Image {
        source: @image-url("imgs/notes/A#5.svg");
        horizontal-alignment: center;
        vertical-alignment: center;
    }
    
    if note == "B5" : Image {
        source: @image-url("imgs/notes/B5.svg");
        horizontal-alignment: center;
        vertical-alignment: center;
    }
    
    if note == "C6" : Image {
        source: @image-url("imgs/notes/C6.svg");
        horizontal-alignment: center;
        vertical-alignment: center;
    }
    
    if note == "C#6" : Image {
        source: @image-url("imgs/notes/C#6.svg");
        horizontal-alignment: center;
        vertical-alignment: center;
    }
    
    if note == "D6" : Image {
        source: @image-url("imgs/notes/D6.svg");
        horizontal-alignment: center;
        vertical-alignment: center;
    }
}
