export component SongPopup inherits PopupWindow {
    in-out property <string> songPlaying;
    close-policy: close-on-click-outside;
    Rectangle { 
        height:100%; width: 100%; 
        background: #884fbbe9; 
        border-width: 4px;
        border-color: #a189da;
        border-radius: 30px;
        drop-shadow-blur: 20px;
        drop-shadow-color: #000000aa;
    }

    VerticalLayout {
        alignment: center;
        padding: 16px;
        spacing: 32px;
        HorizontalLayout {
            alignment: space-evenly;
            Text { text: "You Played:"; font-size: 18px; }
        }
        HorizontalLayout {
            alignment: space-evenly;
            Text { text: root.songPlaying; font-size: 36px; font-weight: FontWeight.extra-bold; }
        }
    }

    x: 237px; y: 100px; width: 550px; height: 400px;
}