import { Button, VerticalBox, HorizontalBox } from "std-widgets.slint";
import { NoteCanvas } from "components/note-canvas.slint";

component Logo inherits Rectangle {
    width: 100%;

    Image {
        source: @image-url("components/imgs/OcarinaOS.svg");
        width: 256px;
        height: 46.94919455px;
    }
}

////////////////////////////////////////////
// App Window
////////////////////////////////////////////

export component AppWindow inherits Window {
    // Set to true when exporting!
    full-screen: true;
    max-width: 1024px;
    min-height: 600px;
    min-width: 1024px;
    preferred-height: 600px;
    preferred-width: 1024px;
    max-height: 600px;
    background: #3f2954;
    in-out property <string> currentlyPlayingSong: "TEsting again";
    in-out property <[string]> playedNotes;
    in-out property <bool> listening: false;
    callback request-increase-value();

    
    VerticalBox {
        ////////////////////////////////////////////
        // Top Panel
        ////////////////////////////////////////////

        HorizontalBox {
            Button {
                text: "Info";
                clicked => {
                    root.request-increase-value();
                }
            }
            Text {
                width: 800px;
                horizontal-alignment: center;
                vertical-alignment: center;
                text: root.currentlyPlayingSong;
            }
            Button {
                text: "Settings";
                clicked => {
                    root.request-increase-value();
                }
            }
        }
        

        ////////////////////////////////////////////
        // Note Panel
        ////////////////////////////////////////////
        
        NoteCanvas {
            Notes: root.playedNotes;

            Listening: root.listening;
        }

        ////////////////////////////////////////////
        // Logo Panel
        ////////////////////////////////////////////

        Logo{
            
        }
    }
}