#!/bin/sh
# initramfs splash module

ocarina_splash_enabled() {
    return 0
}

ocarina_splash_run() {
    echo "SPLASH: starting" > /dev/console
    /usr/bin/ocarina-splash &
    echo "SPLASH: started pid $!" > /dev/console
}

ocarina_splash_stop() {
    killall ocarina-splash 2>/dev/null || true
}